spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poc_test
    username: ap
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      example:
        demo: DEBUG
